language: rust
rust: 
  - stable

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang
    
install:
  - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
  
script:
  - cargo test --all
  - cargo build --release
  - cargo bench --all

env:
  global:
  - RUST_BACKTRACE=1
  - CC="clang"
