[package]
name = "robin"
version = "0.1.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "hycon_core"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"
protoc = "2.0.4"


[build-dependencies.protoc-rust]
git = "https://github.com/ChosunOne/rust-protobuf"
branch = "v2.0"

[build-dependencies.protobuf-codegen]
git = "https://github.com/ChosunOne/rust-protobuf"
branch = "v2.0"

[dependencies]
neon = "0.2.0"
rust-base58 = "0.0.4"
blake2-rfc = "0.2.18"
secp256k1 = "0.10.0"
bytes = "0.4.9"
protobuf = "2.0.4"
cryptonight-rs = "^0.2"
rand = "0.5.5"
serde_json = "1.0.26"
serde_derive = "1.0.72"
serde = "1.0.72"
openssl = {version = "0.10.11", features = ["vendored"]}
hex = "0.3.2"
tiny-keccak = "1.4.2"
lazy_static = "1.1.0"
byteorder = "1.2.6"

[dependencies.uuid]
version = "0.6.5"
features = ["v4"]