[package]
name = "robin"
version = "0.1.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>, Niall Moore <niall@hycon.io>"]
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "hycon_core"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"
protoc = "2.0.4"
protoc-rust-no-elision = "2.0.4"
protobuf-codegen-no-elision = "2.0.4"

[dependencies]
neon = "0.2.0"
rust-base58 = "0.0.4"
blake2-rfc = "0.2.18"
secp256k1 = "0.10.0"
bytes = "0.4.9"
protobuf = "2.0.4"
mock-it = "0.2.0"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
cryptonight-rs = "^0.2"
rand = "0.5.5"
serde_json = "1.0.26"
serde_derive = "1.0.72"
serde = "1.0.72"
openssl = {version = "0.10.11", features = ["vendored"]}
hex = "0.3.2"
tiny-keccak = "1.4.2"
lazy_static = "1.1.0"
double = "0.2.2"
byteorder = "1.2.6"
rocksdb= "0.10.1"

[dependencies.uuid]
version = "0.6.5"
features = ["v4"]
