[package]
name = "rustyphoenix"
version = "0.1.0"
authors = ["Josiah Evans <koreanhalo@gmail.com>"]
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "rustyphoenix"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"
protoc = "2.0.4"


[build-dependencies.protoc-rust]
git = "https://github.com/ChosunOne/rust-protobuf"
branch = "v2.0"

[build-dependencies.protobuf-codegen]
git = "https://github.com/ChosunOne/rust-protobuf"
branch = "v2.0"

[dependencies]
neon = "0.2.0"
rust-base58 = "0.0.4"
blake2-rfc = "0.2.18"
merkle = "1.7.0"
secp256k1 = "0.10.0"
bytes = "0.4.9"
protobuf = "2.0.4"
cryptonight-rs = "^0.2"
rand = "0.5.5"
rustc-serialize = "0.3.24"